import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from "react";
import coingecko from './api/coingecko';

const Home: NextPage = () => {

  const coingeckoUrl = (exchange: string) => {
    return `https://api.coingecko.com/api/v3/exchanges/${exchange}`;
  };

  // const response = await coinGecko.get("/coins/markets/", {
  //   params: {
  //     vs_currency: "usd",
  //     ids: watchList.join(","),
  //   },
  // });

  const [ exchanges, setExchanges ] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await coingecko.get(`/exchanges/`, {
          params: {
            ids: "binance",
          },
        });
      // console.log(response.data.slice(0,10))
      const topTenExchangeData = response.data.slice(0,10)
      setExchanges(topTenExchangeData)
    };

    fetchData();
  }, []);
  // const coingeckoFetch = async (exchange) => {
  //   fetch(coingeckoUrl(exchange)).then((response) =>
  //     response.json().then((jsonData) => {
  //       if (buy) {
  //         setTrade({ ...trade, buyData: jsonData });
  //       } else {
  //         setTrade({ ...trade, sellData: jsonData });
  //       }
  //     })
  //   );
  // };

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Button test
      </button>
      {/* <h3>${exchanges}</h3> */}
    </>
  );

}

export default Home
