import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from "react";
import Exchange from '../components/Exchange';
import coingecko from './api/coingecko';

const Home: NextPage = () => {

  const [ exchanges, setExchanges ] = useState<any[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await coingecko.get(`/exchanges/`, {
          params: {
            ids: "binance",
          },
        });
      // console.log(response.data.slice(0,10))
      const topTenExchangeData = response.data.slice(0,10)
      setExchanges(topTenExchangeData)
    };

    fetchData();
  }, []);
  // const coingeckoFetch = async (exchange) => {
  //   fetch(coingeckoUrl(exchange)).then((response) =>
  //     response.json().then((jsonData) => {
  //       if (buy) {
  //         setTrade({ ...trade, buyData: jsonData });
  //       } else {
  //         setTrade({ ...trade, sellData: jsonData });
  //       }
  //     })
  //   );
  // };

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h3>${exchanges}</h3> */}
      <ul>
        {exchanges.map((exchange) => {
          return <Exchange key={exchange.id} exchange={exchange}/>
        })}
      </ul>
    </>
  );

}

export default Home
