import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from "react";
import Exchange from './ExchangeRow';
import coingecko from '../pages/api/coingecko';
import ExchangeRow from './ExchangeRow';

const Directory: NextPage = () => {

  const [ exchanges, setExchanges ] = useState<any[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await coingecko.get(`/exchanges/`, {
          params: {
            ids: "",
          },
        });
      // console.log(response.data.slice(0,10))
      const topTenExchangeData = response.data.slice(0,10)
      setExchanges(topTenExchangeData)
    };

    fetchData();
  }, []);

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h3>${exchanges}</h3> */}
      <ul>
        {exchanges.map((exchange) => {
          // TODO: pass in full data as prop to use in dynamic rendering
          return <ExchangeRow key={exchange.id} exchange={exchange} image={exchange.image}/>
        })}
      </ul>
    </>
  );

}

export default Directory
